### ISSUE TITLE
Remove exposed ports

### ISSUE THREAD

**Issue by lukecampbell** [ioos/catalog-docker-base#1]
The parent dockerfile had exposed port 80. We need to remove it. I think you can override it by just doing

```
EXPOSE
```

**Comment by benjwadams** [comment]
The above invocation is invalid syntax.  There is discussion on Docker to have an "UNEXPOSE"-like command, but thus far it is not present in the features.   AFAIK the only way to remove a port expose is to modify the parent Dockerfile, which might be a little overkill.
