### ISSUE TITLE
Race Conditions for Container Startup

### ISSUE THREAD

**Issue by lukecampbell** [ioos/catalog-docker-base#3]
If you startup all the containers simultaneously (like with compose) for the very first time with fresh volumes, a race-condition can occur which will corrupt the database.

**Comment by benjwadams** [comment]
Is this condition still present?

**Comment by lukecampbell** [comment]
yes

**Comment by lukecampbell** [comment]
CKAN, PyCSW and the harvesters all try to write and initialize the database concurrently on startup. If any of them succeed before CKAN, the db gets corrupted.

**Comment by benjwadams** [comment]
Should be fixed by
 https://github.com/ioos/catalog-docker-ckan-harvest/pull/1
https://github.com/ioos/catalog-docker-pycsw/pull/1

Please close for the time being; it looks like I can't close issues on this repo.
