### ISSUE TITLE
Update Dockerfile to use new CKAN base image

### ISSUE THREAD

**Issue by benjwadams** [ioos/catalog-docker-base#49]
The Dockerfile should be updated to use the new CKAN base image, located here:  https://github.com/ckan/ckan-docker-base/blob/main/ckan-2.10/base/Dockerfile

This may help other problems such as https://github.com/ioos/catalog-ckan/issues/246 as a side effect.
This will require rewriting the Dockerfile to adopt Alpine conventions, packages, etc, instead of Debian's.

**Comment by mwengren** [comment]
@benjwadams says this is ready to be handed off to @nguyandy this week to look into debugging the outstanding Catalog JS/UI issues:

* https://github.com/ioos/catalog-ckan/issues/242
* https://github.com/ioos/catalog-ckan/issues/244
* https://github.com/ioos/catalog-ckan/issues/243

**Comment by mwengren** [comment]
@benjwadams You moved this to review during our Catalog meeting earlier.  I don't think we have a clear understanding of what 'Review' means on our board, however.  Is it complete to the point of being closed from your standpoint?  If so, I'll go ahead and do that.
