### ISSUE TITLE
Resolve SOLR schema persistence issue on restart

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-docker-base#51]
@benjwadams mentioned during today's Catalog meeting that occasionally, on restart, the lastest Solr version will replace the custom schema Catalog uses with the default schema provided by the Solr distribution.  This results in dataset count in Catalog being reset to 0, until the schema can be updated and the search index rebuilt. 

Xref:
* https://github.com/ioos/catalog-docker-base/blob/update_build/contrib/system_scripts/install_solr_schema.bash 
* https://github.com/ckan/ckan-solr

**Comment by benjwadams** [comment]
I think this may have to do with volume persistence, but I'm not entirely sure.   The updated Solr images have some changed directories.  When the container is removed or recreated anew, the index is zeroed out.

**Comment by benjwadams** [comment]
I believe https://github.com/ioos/catalog-docker-base/commit/2971e89180facfb9fb98bafad0c851cdad6b448e may address this issue.  I upgraded the Solr version via a Docker container upgrade and the location of the index changed.
